SELECT*FROM MEMBER;

SELECT*FROM MEMBER
WHERE USERID = 'stpn';

DESC MEMBER;

DELETE FROM MEMBER;

SELECT*FROM MEMBER WHERE USERID LIKE '%'||'a'||'%' ORDER BY USERID;  --문자열 연결
SELECT*FROM MEMBER WHERE BIRTHYEAR BETWEEN 0 AND 3000 ORDER BY USERID;

UPDATE MEMBER SET PASSWD = '9991', BIRTHYEAR = 2000 WHERE USERID = 'qwee';

COMMIT;

INSERT INTO MEMBER (USERID,PASSWD,BIRTHYEAR)  VALUES ('KIM','1111',920101);
