--ªÛ«∞ ∆«∏≈

--ªÛ«∞ ∏∂Ω∫≈Õ (∫Œ∏)
DROP TABLE ITEM;  --≈◊¿Ã∫Ì¿ª ªË¡¶, ªË¡¶«ÿº≠ ¥ŸΩ√ ∏∏µÈ∏È µ 

CREATE TABLE ITEM ( -- ≈◊¿Ã∫Ì ª˝º∫
ITEMCODE VARCHAR2(13) NOT NULL,   --ªÛ«∞ ƒ⁄µÂ
ITEMNAME VARCHAR2(100) NOT NULL ,   --ªÛ«∞∏Ì
PRICE NUMBER(7) NOT NULL,  
BIGO VARCHAR2(100) NULL, -- ∫Ò∞Ì
REGDATE DATE DEFAULT SYSDATE, --µÓ∑œ¿œ¿⁄  
CONSTRAINT PK_ITEMCODE PRIMARY KEY(ITEMCODE)  --PK  («œ≥™∏∏ ¿‚æ∆æﬂ ¿Ø¿œ≈∞)
);

DESC ITEM; --º”º∫ »Æ¿Œ
SELECT * FROM ITEM;


--ºº¿œ¡Ó ≈◊¿Ã∫Ì (¿⁄Ωƒ)
DROP TABLE SALES;  --≈◊¿Ã∫Ì ªË¡¶

CREATE TABLE SALES(
SALEDATE VARCHAR2(10),  --∆«∏≈≥Ø¬•
SEQ NUMBER(5),  --º¯π¯
ITEMCODE VARCHAR2(13) NOT NULL,  --æ∆¿Ã≈€ƒ⁄µÂ
QTY NUMBER(3) NOT NULL,  -- ∆«∏≈ºˆ∑Æ
AMOUNT NUMBER(10) NOT NULL,  --∆«∏≈±›æ◊
REGDATE DATE DEFAULT SYSDATE,  --µÓ∑œ¿œ¿⁄
CONSTRAINT PK_SALEDATE_SEQ PRIMARY KEY (SALEDATE,SEQ),  -- pk
CONSTRAINT FK_ITEMCODE_ITEM FOREIGN KEY (ITEMCODE) REFERENCES ITEM(ITEMCODE)  --∆˜∏µ≈∞ //æÓ∂≤ ƒ⁄µÂ∏¶ ¬¸¡∂«“¡ˆ æÍ±‚ «ÿ¡‡æﬂ¥Ô, ¬¸¡∂∞° µ«¥¬ ≈∞¥¬ ¿Ø¿œ≈∞
);

DESC SALES; --º”º∫ »Æ¿Œ
SELECT * FROM SALES;

--ªÛ«∞ ∏∂Ω∫≈Õ √ﬂ∞°
INSERT INTO ITEM (ITEMCODE,ITEMNAME,PRICE) VALUES ('8801','ªÁ¿Ã¥Ÿ',1000);
INSERT INTO ITEM (ITEMCODE,ITEMNAME,PRICE) VALUES ('8802','ƒ›∂Û',1200);
INSERT INTO ITEM (ITEMCODE,ITEMNAME,PRICE) VALUES ('8803','∫Ú∏∆',6000);
INSERT INTO ITEM (ITEMCODE,ITEMNAME,PRICE) VALUES ('8804','√Ú∆ƒÆèΩ∫',500);
SELECT * FROM ITEM;

--∆«∏≈ √ﬂ∞°
INSERT INTO SALES (SALEDATE,SEQ,ITEMCODE,QTY,AMOUNT) VALUES ('2021-04-29',1,'8801',2,2*1000);
INSERT INTO SALES (SALEDATE,SEQ,ITEMCODE,QTY,AMOUNT) VALUES ('2021-04-29',2,'8802',5,5*1200);
INSERT INTO SALES (SALEDATE,SEQ,ITEMCODE,QTY,AMOUNT) VALUES ('2021-04-30',2,'8804',5,5*500);
INSERT INTO SALES (SALEDATE,SEQ,ITEMCODE,QTY,AMOUNT) VALUES ('2021-04-30',3,'8803',6,6*6000);
INSERT INTO SALES (SALEDATE,SEQ,ITEMCODE,QTY,AMOUNT) VALUES ('2021-04-31',4,'8803',3,2*6000);

SELECT * FROM SALES;


--¿œ¿œ ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ
SELECT S.SALEDATE, S.SEQ, S.ITEMCODE, I.ITEMNAME, S.QTY, S.AMOUNT
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE);


--¿œ¿œ ªÛ«∞∫∞ ¡˝∞Ë ∆«∏≈
SELECT S.SALEDATE, S.ITEMCODE, MAX(I.ITEMNAME) ITEMNAME, SUM(S.QTY) QTY, SUM(S.AMOUNT) AMOUNT
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
GROUP BY S.SALEDATE, S.ITEMCODE 
HAVING SUM(S.QTY)>3  
ORDER BY S.SALEDATE, S.ITEMCODE;


--ªÛ«∞∫∞ ¡˝∞Ë ∆«∏≈

SELECT S.ITEMCODE, I.ITEMNAME, SUM(S.QTY) QTY, SUM(S.AMOUNT) AMOUNT
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
GROUP BY S.ITEMCODE, I.ITEMNAME
ORDER BY S.ITEMCODE;


--¿œ¿œ ªÛ«∞∫∞ ¡˝∞Ë ∆«∏≈
SELECT S.SALEDATE, S.ITEMCODE, MAX(I.ITEMNAME) ITEMNAME, SUM(S.QTY) QTY, SUM(S.AMOUNT) AMOUNT
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
GROUP BY S.SALEDATE, S.ITEMCODE  --±◊∑Ï¿∏∑Œ π≠æÓº≠ ∞·«’
HAVING SUM(S.QTY)>3   --±◊∑ÏπŸ¿Ã ¿Ã»ƒ¿« ¡∂∞«πÆ, æÀ∏Ææ∆Ω∫∏Ì¿Ã ª˝º∫¿¸¿ÃæÓº≠ SUM
ORDER BY S.SALEDATE, S.ITEMCODE;


--º≠∫Íƒı∏Æ
--∆Ú±’∆«∏≈ºˆ∑Æ∫∏¥Ÿ ¿˚¿∫ ∆«∏≈ ªÛ«∞ ∏ÆΩ∫∆Æ
--1) ∆Ú±’ ∆«∏≈ ºˆ∑Æ¿ª ±∏«‘(AVGQTY)
--2) ∆Ú±’ πÃ¥ﬁ ªÛ«∞ ∏ÆΩ∫∆Æ

--∆Ú±’ ∆«∏≈ ºˆ∑Æ ±∏«œ±‚
SELECT AVG(QTY) AVGQTY 
FROM SALES;

--∆Ú±’ πÃ¥ﬁ ªÛ«∞ ∏ÆΩ∫∆Æ ±∏«œ±‚
SELECT S.*, I.ITEMNAME
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
WHERE QTY < 4;


--WHERE¿˝ º≠∫Íƒı∏Æ
--«œ≥™∑Œ ∏∏µÈ±‚ (º≠∫Í ƒı∏Æ) ƒı∏ÆπÆ æ»ø° ºø∑∫∆Æ ∂« Ω·πˆ∏Æ±‚~
SELECT S.*, I.ITEMNAME
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
WHERE QTY < (SELECT AVG(QTY) AVGQTY FROM SALES);

--SELECT¿˝ º≠∫Íƒı∏Æ
--ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ + ∆Ú±’ ∆«∏≈ ºˆ∑Æ  
SELECT S.*, I.ITEMNAME,(SELECT AVG(QTY) AVGQTY FROM SALES) AS AVGOTY
FROM SALES S INNER JOIN ITEM I ON(S.ITEMCODE = I.ITEMCODE);


--¥ıπÃ ≈◊¿Ã∫Ì¿ª ¿ÃøÎ«ÿº≠ ≈◊Ω∫∆Æ(º“ºˆ¡° ¿⁄∏£±‚)
SELECT TRUNC(2.6666,2) 
FROM DUAL;  --¥ıπÃ ≈◊¿Ã∫Ì

--ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ + ∆Ú±’ ∆«∏≈ ºˆ∑Æ  (º“ºˆ¡°¿⁄∏£±‚)
SELECT S.*, I.ITEMNAME,TRUNC( (SELECT AVG(QTY) AVGQTY FROM SALES),2) AS AVGOTY
FROM SALES S INNER JOIN ITEM I ON(S.ITEMCODE = I.ITEMCODE);


--FROM¿˝ º≠∫Íƒı∏Æ
--ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ + ªÛ«∞∫∞ ∆«∏≈ ºˆ∑Æ ∆Ú±’
--ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ
SELECT S.*,I.ITEMNAME
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE);

--ªÛ«∞∫∞ ∆«∏≈ ºˆ∑Æ ∆Ú±’
SELECT ITEMCODE, AVG(QTY) QTY  --¿Ã∏ß¿ª QTY∑Œ πŸ≤ﬁ
FROM SALES 
GROUP BY ITEMCODE;

--ªÛ«∞ ∆«∏≈ ∏ÆΩ∫∆Æ + ªÛ«∞∫∞ ∆«∏≈ ºˆ∑Æ ∆Ú±’ // «¡∑“¿˝ ¡∂¿Œ  //¥ı∫Ì¡∂¿Œ
SELECT S.*,I.ITEMNAME, IA.QTY QTYAVG--¿Ã∏ß¿ª QTYAVG∑Œ πŸ≤ﬁ
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE)
INNER JOIN (SELECT ITEMCODE,AVG(QTY) QTY FROM SALES GROUP BY ITEMCODE) IA ON(S.ITEMCODE = IA.ITEMCODE);


--º≠∫Íƒı∏Æ ø¨Ω¿
--ªÛ«∞ ∏∂Ω∫≈Õø°º≠ ∆«∏≈µ«¥¬ ∆Ú±’ ¥‹∞°∫∏¥Ÿ ≈´∞Õ
SELECT S.*,I.ITEMNAME
FROM SALES S INNER JOIN ITEM I ON (S.ITEMCODE = I.ITEMCODE);

--ªÛ«∞ ∏∂Ω∫≈Õ
SELECT *
FROM ITEM;

--ªÛ«∞∏∂Ω∫≈Õ¿« ∆Ú±’ ¥‹∞°
SELECT AVG(PRICE)
FROM ITEM;

--√÷¡æ
SELECT *
FROM ITEM
WHERE PRICE > (SELECT AVG(PRICE) FROM ITEM);


--ªÛ«∞ ∏∂Ω∫≈Õ + √— ∆«∏≈±›æ◊
SELECT *
FROM ITEM;

SELECT SUM(AMOUNT) AVGQTY 
FROM SALES;

--√÷¡æ
SELECT I.*, CH.AVGQTY
FROM ITEM I INNER JOIN SALES S ON (I.ITEMCODE = S.ITEMCODE)
INNER JOIN (SELECT SUM(AMOUNT) AVGQTY FROM SALES) CH ON (I.ITEMCODE = S.ITEMCODE);


--√÷¡æ (ºø∑∫∆Æ º≠∫Íƒı∏Æ)
SELECT i.*, (SELECT SUM(AMOUNT) AVGQTY FROM SALES)
FROM ITEM i;  --ªÛº”∞¸∞Ëø° ¿÷¥¬ ƒ√∑≥¿Ã ¡ﬂ∫πµ«æÓ ¿Ã∏ß¿ª µ˚∑Œ ¡ˆ¡§ §°§°



--ªÛ«∞ ∏∂Ω∫≈Õ + ªÛ«∞∫∞ ∆«∏≈ ±›æ◊  --¥Ÿ«‘
SELECT I.ITEMCODE , SUM(AMOUNT) AVGQTY
FROM ITEM I INNER JOIN SALES S ON (I.ITEMCODE = S.ITEMCODE) 
GROUP BY I.ITEMCODE;

--ªÛ«∞ ∞°∞›∏∏
SELECT ITEMCODE, SUM(AMOUNT) AS SUM
FROM SALES 
GROUP BY ITEMCODE;

-- √÷¡æ
SELECT I.*, CC.AC
FROM ITEM I INNER JOIN (SELECT ITEMCODE, SUM(AMOUNT) AS AC FROM SALES GROUP BY ITEMCODE) CC ON (I.ITEMCODE = CC.ITEMCODE);


--øÎ»∆¿Ã∞° æÀ∑¡¡ÿ∞≈
SELECT I.*, S.SUM
FROM ITEM I INNER JOIN (SELECT ITEMCODE, SUM(AMOUNT) SUM FROM SALES GROUP BY ITEMCODE) S ON (I.ITEMCODE = S.ITEMCODE);

--«ÿºÆ
--ªÛ«∞ ∏∂Ω∫≈Õ
SELECT *
FROM ITEM;

--ªÛ«∞∫∞ ∆«∏≈ ±›æ◊
SELECT ITEMCODE, SUM(AMOUNT) SUM 
FROM SALES 
GROUP BY ITEMCODE;

--√÷¡æ «ÿºÆ
SELECT I.*, NVL(S.AMOUNT,0) AMOUNT --æÓ∏∂øÓ∆Æ ∞™¿Ã ≥Œ ¿Ã∂Û∏È 0¿∏∑Œ √≥∏Æ
FROM ITEM I LEFT JOIN (SELECT ITEMCODE, SUM(AMOUNT) AMOUNT FROM SALES GROUP BY ITEMCODE) S ON (I.ITEMCODE = S.ITEMCODE)
ORDER BY I.ITEMCODE;
--¿ßø°≤®¥¬ µøµÓ¡∂¿Œ¿∏∑Œ «œ≥™µµ æ»∆»∏Æ∏È æ»≥™ø√ºˆ ¿÷¿∏π«∑Œ æ∆¿Ã≈€¿ª ¡ﬂΩ…¿∏∑Œ ¡∂¿Œ (∑π«¡∆Æ ¡∂¿Œ)


--√ﬂ∞°  (≥Ø¬• ¡∂∞« √ﬂ∞°)
SELECT I.ITEMCODE, I.ITEMNAME, I.PRICE, NVL(S.AMOUNT,0) AMOUNT, REGDATE, NVL(I.BIGO,' ') BIGO
FROM ITEM I LEFT JOIN 
        (SELECT ITEMCODE, SUM(AMOUNT) AMOUNT 
        FROM SALES 
        WHERE SALEDATE = '2021-04-30'
        GROUP BY ITEMCODE) S 
        ON (I.ITEMCODE = S.ITEMCODE)
ORDER BY I.ITEMCODE;





SELECT *
FROM ITEM;
SELECT *
FROM SALES;






COMMIT;



















