--MEMBER 회원 테이블 생성

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
USERID VARCHAR2(20),
PASSWD VARCHAR2(20) NOT NULL,
BIRTHYEAR NUMBER(4),
REGDATE DATE DEFAULT SYSDATE,
CONSTRAINT PK_USERID PRIMARY KEY (USERID)
);

SELECT * FROM MEMBER;

--SelectList

--SelectOne
SELECT * FROM MEMBER
WHERE USERID = 'SSSS';

--데이터 추가
INSERT INTO MEMBER (USERID,PASSWD,BIRTHYEAR) VALUES('SSSS','1111',0606);
INSERT INTO MEMBER (USERID,PASSWD,BIRTHYEAR) VALUES('QQQQ','2222',0707);
INSERT INTO MEMBER (USERID,PASSWD,BIRTHYEAR) VALUES('DDDD','3333',0808);
INSERT INTO MEMBER (USERID,PASSWD,BIRTHYEAR) VALUES('EEEE','4444',0505);

--데이터 수정
UPDATE MEMBER
SET PASSWD = '0000',
BIRTHYEAR = 2020
WHERE USERID = 'SSSS';

--데이터 삭제
DELETE FROM MEMBER 
WHERE USERID = 'QQQQ';

SELECT * FROM MEMBER
ORDER BY USERID;

COMMIT;  

ROLLBACK;



